# Generated by Django 4.2.2 on 2023-06-27 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_action_payload_room_sensor_user_delete_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sink_id', models.CharField(max_length=50)),
                ('source_address', models.BigIntegerField()),
                ('tx_time_ms_epoch', models.BigIntegerField()),
                ('data', models.JSONField()),
                ('event_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='payload',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='payload',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='location',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sensors',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='users',
        ),
        migrations.AddField(
            model_name='sensor',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Payload',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sensor'),
        ),
    ]
