# Generated by Django 4.2.2 on 2023-06-27 14:42

from django.db import migrations

def create_rooms_and_sensors(apps, schema_editor):
    Room = apps.get_model('main', 'Room')
    Sensor = apps.get_model('main', 'Sensor')
    rooms_and_sensors = [
        {
            "room": "Classroom 1",
            "sensors": ["Temperature", "Humidity", "Occupancy/Presence"]
        },
        {
            "room": "Classroom 2",
            "sensors": ["Temperature", "Humidity", "Occupancy/Presence"]
        },
        {
            "room": "Classroom 2",
            "sensors": ["Temperature", "Humidity", "Occupancy/Presence"]
        },
        {
            "room": "Bathroom",
            "sensors": ["Temperature", "Humidity", "Occupancy/Presence", "Smoke/Carbon Dioxide/Gas Toxicity Detection"]
        },
        {
            "room": "Computer Lab",
            "sensors": ["Temperature", "Humidity", "Occupancy/Presence", "Shock Detection"]
        },
        {
            "room": "Library",
            "sensors": ["Temperature", "Humidity", "Occupancy/Presence"]
        },
        {
            "room": "Staff Room",
            "sensors": ["Temperature", "Humidity", "Occupancy/Presence"]
        },
        {
            "room": "Principal's Office",
            "sensors": ["Temperature", "Humidity", "Occupancy/Presence"]
        },
        {
            "room": "Multi-purpose Hall",
            "sensors": ["Temperature", "Humidity", "Occupancy/Presence", "Pressure", "Shock Detection"]
        },
    ]
    
    for room_and_sensors in rooms_and_sensors:
        room, created = Room.objects.get_or_create(name=room_and_sensors['room'])
        for sensor_type in room_and_sensors['sensors']:
            Sensor.objects.get_or_create(room=room, sensor_type=sensor_type, sensor_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sensordata_remove_payload_sensor_remove_payload_user_and_more'),
    ]

    operations = [
        migrations.RunPython(create_rooms_and_sensors),
    ]

