# Generated by Django 4.2.2 on 2023-06-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230628_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
